### ISSUE TITLE
Very long wait time on shutdown (more than 5 seconds)

### ISSUE THREAD

**Issue by Wadimich** [getnamo/socketio-client-unreal#228]
I have UE 4.23 version of this plugin and encounter bad condition. When my dedicated server or game closing - it is waiting SocketIO Client plugin shutdown. It takes more than 5 seconds, so internal code does break from loop.

I want to know, why it takes so much time, will i encounter any problems because it won't let finish it's job.

**Comment by getnamo** [comment]
If you're using FSocketIONative, ensure you're using ```ISocketIOClientModule::Get().NewValidNativePointer();``` and ```ISocketIOClientModule::Get().ReleaseNativePointer(Socket);``` from e.g. https://github.com/getnamo/socketio-client-ue4#example-fsocketionative-custom-game-instance. 

If you don't the connections will release when you destroy/release the native pointer. Otherwise they all queue when the program scope goes out (on shutdown) in a multithreaded manner.

**Comment by Wadimich** [comment]
I use blueprints. Is there a way i can handle this from bp?

**Comment by getnamo** [comment]
How are you allocating your connections in BP?

**Comment by Wadimich** [comment]
I have disabled auto connection and connect manually. Config set to persist between worlds. To reproduce - i just need to start dedicated server, wait until it does things - then shutdown it. On shutdown it hangs 5 seconds, which is long for such job.

**Comment by getnamo** [comment]
Closing due to age, re-open if problem persists in new plugin versions.
